### PR TITLE
image annotation

### LINKED ISSUE #41: Image Annotation Question Should Show Preview of Annotated Image
### Description

The image annotation question type should display a preview of the annotated image next to the "Answered" status.

### Reproduction

Have an image annotation question.

### Expected behavior

Should show a preview of the annotations.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #43: Improve Automatic Dismiss of QuestionnaireSheet Logic
### Description

The current version of the `QuestionnaireSheet` automatically dismisses the sheet once the `resultHandler` is completed. This causes an issue that apps can not display error messages (see LLMonFHIR) if the code in the result handler fails.

### Reproduction

Embed the `QuestionnaireSheet` in a few that tries to display an error alert if code in the result handler fails.

### Expected behavior

The `resultHandler` should either be throwing and the sheet should display the localized error in the UI itself (which might become quite complicated) or the automatic dismissed should be removed and rather be handled by the UI handling the sheet in the result handler. Or a combination of both.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by lukaskollmer**
# image annotation

## :recycle: Current situation & Problem
we want to be able to support an "Annotate this image!" question kind

## :gear: Release Notes
- new image annotation question kind
- fixes #43
- closes #41

## :books: Documentation
*todo*

## :white_check_mark: Testing
we have new unit and UI tests for some of the new things (eg branching logic, FHIR conversion, UI logic, etc), but some things are still missing (tracked via #44)

## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

## Summary by CodeRabbit

* **New Features**
  * Image annotation tasks: load bundled images, draw/select regions, preview and save/reset annotations, include annotated images in exports.

* **Bug Fixes**
  * Corrected condition evaluation and input validation for annotation/file-attachment tasks.
  * Questionnaire sheet no longer auto-dismisses after completion (presenter must handle dismissal).

* **Improvements**
  * Expanded localization, refined button states/feedback, background styling, and accessibility labels.

* **Chores**
  * Raised iOS minimum to 18.0 and updated dependencies.

### CODE REVIEW

**Review by PSchmiedmayer — COMMENTED** [review]
Thank you for working on this; happy to review once the TODOs are resolved and we have it in a stable state.

**Comment by lukaskollmer** [comment]
@PSchmiedmayer the TODOs are resolved and this is in a stable state

File: Sources/SpeziQuestionnaire/Model/Task.swift [hunk 1]
```diff
@@ -83,6 +85,8 @@ extension Questionnaire.Task {
         case numeric(_ config: NumericTaskConfig)
         /// A task that lets the user select photos and other files.
         case fileAttachment(_ config: FileAttachmentConfig)
+        /// A task that asks the user to annotate an image
+        case annotateImage(_ config: AnnotateImageConfig)
```
Comment (lukaskollmer) [inline Sources/SpeziQuestionnaire/Model/Task.swift:89]: @PSchmiedmayer this case (and the config struct below) will get removed once we have support for custom task definitions with custom task view injection. until then it will stay.

the storing of the annotation respone is already done via a "custom response type" API; we just don't yet have this on the definition side of things

Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaire/Model/Task.swift:89]: Sounds like a good approach; thank you @lukaskollmer 👍

File: Sources/SpeziQuestionnaire/UI/Tasks/TaskView+AnnotateImage.swift [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+                    Spacer()
+                    ImageAnnotationView(
+                        image: image,
+                        drawing: $response.drawing,
+                        drawingScale: $response.scaleFactor,
+                        tool: selectedRegion.map { PKInkingTool(ink: AnnotateImageView.ink(for: $0), width: 2) } ?? .init(.crayon)
+                    )
+                    Spacer()
+                }
+                .padding(.horizontal)
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/UI/Tasks/TaskView+AnnotateImage.swift:161]: We might want to reduce the padding a bit. And how do we ensure that if it is a very long image, a user can still scroll in a good way and/or it doesn't go beyond the screen size?

File: Sources/SpeziQuestionnaire/UI/Tasks/TaskView+Choice.swift [hunk 3]
```diff
@@ -19,6 +19,10 @@ extension TaskView {
         var body: some View {
             ForEach(config.options) { option in
                 Row(task: task, config: config, option: option, response: $response)
+                    .sensoryFeedback(trigger: response.value.choiceValue.selectedOptions) { _, _ in
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/UI/Tasks/TaskView+Choice.swift:22]: Great addition!

File: Sources/SpeziQuestionnaire/UI/QuestionnaireSectionView.swift [hunk 4]
```diff
@@ -107,13 +108,14 @@ struct QuestionnaireSectionView<Header: View>: View {
     
     @ViewBuilder private var toolbarDoneButton: some View {
         if #available(iOS 26, *) {
-            AsyncButton(role: .confirm) {
+            AsyncButton(role: .confirm, state: $viewState) {
                 await resultHandler(.completed(responses))
             } label: {
+                // ISSUE the color here is still black in dark mode; but the Continue button at the bottom of the Form is (correctly) white?!!
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/UI/QuestionnaireSectionView.swift]: TODO to create an issue for this?

File: Sources/SpeziQuestionnaire/UI/ViewFormMatchingBackgroundModifier.swift [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+import class UIKit.UIColor
+
+
+private struct ViewFormMatchingBackgroundModifier: ViewModifier {
+    @Environment(\.colorScheme) private var colorScheme
+    
+    func body(content: Content) -> some View {
+        // It seems that this (using background vs backgroundStyle) depending on light/dark mode is what we need to do
+        // in order to have the view background match the form background...
+        // QUESTION(@lukas) why is this the case?
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/UI/ViewFormMatchingBackgroundModifier.swift]: Probably also good to either create an issue for this or investigate further?

File: Package.swift [hunk 6]
```diff
@@ -24,12 +24,13 @@ let package = Package(
         .library(name: "XCTSpeziQuestionnaire", targets: ["XCTSpeziQuestionnaire"])
     ],
     dependencies: [
-        .package(url: "https://github.com/StanfordSpezi/SpeziViews.git", from: "1.12.11"),
+        .package(url: "https://github.com/StanfordSpezi/SpeziViews.git", branch: "lukas/canvas-view-changes"),
```
[the remark this answers is not in the document]
Comment (PSchmiedmayer) [reply Package.swift]: @lukaskollmer TODO to resolve this before a merge.

**Review by PSchmiedmayer — APPROVED** [review]
Thank you @lukaskollmer; happy to see this merged 🚀

File: Sources/SpeziQuestionnaire/UI/Tasks/TaskView+AnnotateImage.swift (hunk 2 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/Tasks/TaskView+AnnotateImage.swift:161]: currently, if you have a super tall image it gets scaled down to fit the maximum available vertical space (ie, it just ends up somewhat narrow).

the region selection `Form` at the bottom of the sheet will always have height 150, and the image annotation view above is sized around that.

IMO this is ok for the time being; a future direction here would be to have a bottom drawer sheet type of situation to select the region (and simply omit it entirely if there is only one region), and allow zoom via a 2 finger gesture; this would then implicitly also allow scrolling via a 2 finger gesture.

File: Sources/SpeziQuestionnaire/UI/QuestionnaireSectionView.swift (hunk 4 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/QuestionnaireSectionView.swift]: it's actually not an issue, i think. you get the same behaviour when placing a regular `Button` into a toolbar and giving it a glass&prominent style

File: Sources/SpeziQuestionnaire/UI/ViewFormMatchingBackgroundModifier.swift (hunk 5 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/ViewFormMatchingBackgroundModifier.swift]: not actually an issue; more of a question i posed to myself at the time (this modifier is taken from MHC). will move the whole thing into SpeziViews at some point btw

File: Sources/SpeziQuestionnaire/UI/Tasks/TaskView+Choice.swift (hunk 3 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/Tasks/TaskView+Choice.swift:22]: i'm still tinkering with the configs on this; imo the feedback should be much stronge; will see what we can do

File: Sources/SpeziQuestionnaire/UI/ViewFormMatchingBackgroundModifier.swift (hunk 5 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/ViewFormMatchingBackgroundModifier.swift]: UPDATE i played around with this a bit and it seems that simply applying `.background(Color(uiColor: .systemGroupedBackground))` to a view is sufficient. this probably was an issue with older iOS versions. will see if we need to have version-dependent behaviour in here and if yes implement that and then add it to SpeziViews so that MHC can also use it

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift [hunk 7]
```diff
@@ -133,7 +137,7 @@ extension QuestionnaireResponses {
         case .instructional:
             // instructional tasks never collect a response; they are always considered as being complete.
             true
-        case .boolean, .choice, .freeText, .dateTime, .numeric, .fileAttachment:
+        case .boolean, .choice, .freeText, .dateTime, .numeric, .fileAttachment, .annotateImage:
             responses[task.id].value != .none
         }
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift:142]: should be fine bc if the annotation is empty the response value gets sanitized to nil. check again
