### PR TITLE
v2 (native rendering and logic)

### LINKED ISSUE #24: Complete Concurrency Checking
### Problem

With [Swift 6 approaching in a few months](https://forums.swift.org/t/swift-6-0-release-process/70220) and [nightly builds already being available](https://forums.swift.org/t/swift-6-0-nightly-development-snapshots/70936) we should ensure that all our packages are working well with all Swift concurrency checks.

### Solution

[Enable strict concurrency checking](https://www.swift.org/documentation/concurrency/) in the Swift Package in a PR and ensure that we don't have any warnings remaining in the packages as we develop new features or fix bugs from now.

The UI Testing App target should also enable [Enable strict concurrency checking](https://www.swift.org/documentation/concurrency/).

The corresponding PR should fix all related warnings when enabling strict concurrency checking.

### Additional context

We should consider adding `SWIFT_TREAT_WARNINGS_AS_ERRORS = YES` to our general workflows to ensure all warnings are flagged as errors during our CI setup.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #30: Migrate to Swift Testing from XCTest
### Problem

With [Swift Testing](https://github.com/swiftlang/swift-testing) being added to the Swift 6 toolchain and the published images & Xcode already containing it, we should migrate all of our packages towards the modern Swift Testing framework.

### Solution

All unit tests and should migrate from `XCTest` to the new [Swift Testing framework](https://developer.apple.com/xcode/swift-testing/) included in the Swift 6 toolchain. We can follow the documentation article to [migrating a test from XCTest](https://developer.apple.com/documentation/testing/migratingfromxctest).

Contributes working on this issue should first watch the swift-testing WWDC videos:
- [Meet Swift Testing](https://developer.apple.com/videos/play/wwdc2024/10179)
- [Go further with Swift Testing](https://developer.apple.com/videos/play/wwdc2024/10195)

We should take advantage of [test suites](https://developer.apple.com/documentation/testing/organizingtests), [parameterized tests](https://developer.apple.com/documentation/testing/parameterizedtesting), and [parallel testing and optimizing our test suites](https://developer.apple.com/videos/play/wwdc2024/10195?time=1269).

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #31: Bug report: Multiple Choice Free-Text Answer
### Description

When using a multiple choice question and enabling the free-text answer, the "other" contains the textfield for the answer. However, this opens/closes on every other tab. 

### Reproduction

See:
https://github.com/user-attachments/assets/4db5ae11-9272-409d-acef-78497b57766c

### Expected behavior

When selected the textfield should be visible, otherwise not.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #35: native rendering and logic
### Problem

we currently use ResearchKit and ResearchKitOnFHIR for rendering questionnaires.
this is not ideal, because it doesn't support all question types we might want to prompt our users, and because ResearchKit has some other inherent limitations (e.g., w.r.t. to branching and validation logic)

### Solution

we should look into implementing our own, SwiftUI-native questionnaire UI.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by lukaskollmer**
# v2 (native rendering and logic)

## :recycle: Current situation & Problem

closes #35
closes #30
closes #24
closes #31

## :gear: Release Notes
- implemented a fully custom `Questionnaire` model and `QuestionnaireSheet` UI
    - `Questionnaire` represents a questionnaire consisting of tasks (which are grouped into sections), and have validation rules and can be conditionally enabled or disabled
    - FHIR compatibility:
        - a `Questionnaire` can be created from a `ModelsR4.Questionnaire`
        - a `QuestionnaireResponses` object can be turned into a `ModelsR4.QuestionnaireResponse`
- the previous, ResearchKit-based implementation (`QuestionnaireView`) is kept around, but will be deprecated in an upcoming release, and eventually removed

## :books: Documentation
yes

## :white_check_mark: Testing
yes

## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

## Summary by CodeRabbit

* **New Features**
  * New QuestionnaireSheet UI, completion page, file picker, thumbnails, and many task UI components.
  * Full questionnaire model, responses model, condition evaluation, input validation, purge logic.
  * FHIR R4 import/export and added questionnaire catalog entries (GAD‑7, PHQ‑9).

* **Chores**
  * CI/workflow overhaul, static analysis workflow, REUSE manifest, and package/module restructuring.

* **Removed**
  * Timed Walk Test target and associated UI.

* **Tests**
  * New unit and UI test suites for FHIR conversion, conditions, responses, and end-to-end flows.

### CODE REVIEW

File: Sources/SpeziQuestionnaireFHIR/FHIRQuestionnaire+Extensions.swift [hunk 1]
```diff
@@ -0,0 +1,380 @@
...
+        case "allCharacters":
+            return .allCharacters
+        default:
+            Self.logger.warning("Encountered unexpected autocapitalizationType in FHIR extension: \(autocapitalizationTypeString)")
+            return nil
+        }
+    }
+
+    var textContentType: UITextContentType? {
+        guard let contentTypeExtension = getExtensionInQuestionnaireItem(url: SupportedExtensions.keyboardType),
```
Comment (phnagy) [inline Sources/SpeziQuestionnaireFHIR/FHIRQuestionnaire+Extensions.swift]:
```suggestion
        guard let contentTypeExtension = getExtensionInQuestionnaireItem(url: SupportedExtensions.textContentType),
```

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+                return .invalid(message: "Invalid Input")
+            }
+            return .ok
+        case .dateTime(let config):
+            let cal = Calendar.current
+            guard let response = responses[task.id].value.dateValue else {
+                return .ok
+            }
+            switch config.style {
+            case .timeOnly:
```
Comment (phnagy) [inline Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift:86]: Fails for `#expect(validate(hour: 10, minute: 15, minValue: time(hour: 9, minute: 30)) == .ok)`

Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift:86]: fixed; thanks for noticing 🚀

File: Sources/SpeziQuestionnaireFHIR/FHIRQuestionnaire+Extensions.swift (hunk 1 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaireFHIR/FHIRQuestionnaire+Extensions.swift]: thanks for pointing this out; is now fixed (was actually a bug copied over from RKoF; now fixed there as well)

File: Package.swift [hunk 3]
```diff
@@ -20,45 +19,79 @@ let package = Package(
...
+            ],
+            swiftSettings: [
+                .enableUpcomingFeature("ExistentialAny"),
+                .enableUpcomingFeature("InternalImportsByDefault")
             ],
             plugins: [] + swiftLintPlugin()
         ),
         .target(
-            name: "SpeziTimedWalkTest",
+            name: "SpeziQuestionnaireLegacy",
```
Comment (PSchmiedmayer) [inline Package.swift:74]: Let's create an issue that documents to remove this before a 2.0 release; good to keep in the beta releases for now.

File: Sources/SpeziQuestionnaire/Model/Questionnaire.swift [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+            for task in section.tasks {
+                if task.id == taskId { // swiftlint:disable:this for_where
+                    return (section, task)
+                }
+            }
+        }
+        return nil
+    }
+    
+    // TOOD should this include/exclude currently disabled tasks?
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/Model/Questionnaire.swift]: Address TODO?

File: Sources/SpeziQuestionnaire/Model/Questionnaire.swift [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+            self.explainer = explainer
+        }
+    }
+}
+
+
+extension Questionnaire {
+    /// A group of tasks.
+    public struct Section: Hashable, Identifiable, Sendable {
+        public let id: String
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/Model/Questionnaire.swift]: Might make sense to add a title here; good to display in the UI in the future. Maybe also a follow-up issue.

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift [hunk 6]
```diff
@@ -0,0 +1,150 @@
...
+
+private import Foundation
+
+
+extension QuestionnaireResponses {
+    enum ResponseValidationResult: Hashable, Sendable {
+        /// The response provided for the task is ok.
+        case ok
+        /// The response provided for the task is invalid.
+        case invalid(message: String)
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift:17]: It might make sense to think about localization here; at least for the ones that are hard-coded here. Questionnaires themselves might already contain localized error messages? 

Also maybe a follow-up issue.

File: Sources/SpeziQuestionnaire/Model/Task.swift [hunk 7]
```diff
@@ -0,0 +1,367 @@
...
+            }
+            
+            /// The options the user can select from
+            public let options: [Option]
+            /// Whether the user should be offered an "Other" option where they can enter arbitrary text.
+            public let hasFreeTextOtherOption: Bool
+//            /// The maximum number of items that may be selected.
+//            ///
+//            /// Set this value to `1` to enable single-selection; set it to `nil` to enable unlimited multiple selection.
+//            public let selectionLimit: Int?
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/Model/Task.swift]: Remove?

File: Sources/SpeziQuestionnaire/Model/Task.swift [hunk 8]
```diff
@@ -0,0 +1,367 @@
...
+        /// - parameter config: The definition of the choice the user is asked to make.
+        case choice(_ config: ChoiceConfig)
+        /// A task that collects a text response from the user.
+        case freeText(_ config: FreeTextConfig)
+        /// A task that asks the user to select a date and/or time.
+        case dateTime(_ config: DateTimeConfig)
+        /// A task that asks the user for a number.
+        case numeric(_ config: NumericTaskConfig)
+        /// A task that lets the user select photos and other files.
+        case fileAttachment(_ config: FileAttachmentConfig)
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/Model/Task.swift:85]: Follow-up issue to create that covers custom views and integrations here.

File: Sources/SpeziQuestionnaireCatalog/PHQ9.swift
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaireCatalog/PHQ9.swift:1]: Wondering if we want to ship them with the main target or rather as an additional target that can be imported if needed? Could then also be localized in the future 👍

File: Sources/SpeziQuestionnaire/UI/QuestionnaireSectionView.swift [hunk 9]
```diff
@@ -0,0 +1,276 @@
...
+                // but tapping it won't proceed to the next section, but rather will scroll to the missing question
+                .tint(!canContinue ? .some(.gray.secondary) : .none)
+                .listRowInsets(EdgeInsets())
+                // awful but we need to communicate this button's state to the UI test,
+                // and bc it is always enabled we have to do this via the identifier...
+                .accessibilityIdentifier("ContinueButton_canContinue=\(canContinue)")
+            }
+        }
+        .navigationTitle(title)
+//        .navigationSubtitle(<#T##subtitle: Text##Text#>)
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaire/UI/QuestionnaireSectionView.swift]: Remove and/or add section title here?

File: Sources/SpeziQuestionnaireFHIR/Questionnaire+FromFHIR.swift [hunk 10]
```diff
@@ -0,0 +1,491 @@
...
+                minute: (value.time?.minute).map(numericCast),
+                second: (value.time?.second.doubleValue).map(Int.init)
+            ))
+        case .decimal(let value):
+            return .decimal(try unwrap(value.value?.decimal.doubleValue))
+        case .integer(let value):
+            return .integer(Int(try unwrap(value.value?.integer)))
+        case .quantity(let value):
+            // ISSUE: we might need to convert units here? (if the condition uses a different unit than the question
+            throw FHIRConversionError("Quantity values are not yet supported in comparisons")
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaireFHIR/Questionnaire+FromFHIR.swift:483]: Good to create a follow-up issue for this here.

File: Sources/XCTSpeziQuestionnaire/QuestionnaireSheetNavigator.swift
Comment (PSchmiedmayer) [inline Sources/XCTSpeziQuestionnaire/QuestionnaireSheetNavigator.swift:1]: Nice to see all the out of the box UI testing infrastructure!!

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for all the work here; would be great to move all the noted issues + elements that we discussed in the meeting + Slack into issues and create a 2.0 milestone to keep track of them. Nice to see that this is implemented in such a clean way!!

File: Sources/SpeziQuestionnaireCatalog/GAD7.swift [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+//
+// SPDX-License-Identifier: MIT
+//
+
+
+extension Questionnaire {
+    /// Generalized Anxiety Disorder 7 Questionnaire
+    ///
+    /// - SeeAlso: https://adaa.org/sites/default/files/GAD-7_Anxiety-updated_0.pdf
+    public static let gad7 = Self(
```
Comment (PSchmiedmayer) [inline Sources/SpeziQuestionnaireCatalog/GAD7.swift:16]: Looking at this Swift definition here; I am wondering if we should add an overload here that accepts localizable elements if they are passed in as string liberals to enable one to easily define it in Swift + localize it right out of the box without needing to do that in code; I think that would be good to have as a native Swift-based definition logic.

File: Package.swift (hunk 3 above)
Comment (lukaskollmer) [reply Package.swift:74]: the way this currently is resolved, is that we have a `QuestionnaireView` (which is the old implementation) and a `QuestionnaireSheet` (which is the new one).

the `QuestionnaireView` is yet not marked as deprecated, but will be once we have verified the new impl, eg in MHC

File: Sources/SpeziQuestionnaire/Model/Questionnaire.swift (hunk 5 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/Questionnaire.swift]: done; we now display the questionnaire title as the navigation title, and the section title (if set) as the navigation subtitle

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift (hunk 6 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift:17]: 2 things:
- IMO the way localization should be handled is that the app supplying the questionnaires would be required to pass a localized questionnaire into the QuestionnaireSheet.
    - basically like what we currently do with MHC)
    - otherwise, we'd need to turn all UI-surfaced `String` properties throughout the entire `Questionnaire` into `LocalizedStringResources`, but that would prevent us from adding `Codable` support down the road (which IMO is a must-have)
    - we could add a `language` field to the metadata (FHIR has smth similar), though i don't think we'd currently actually need/use this anywhere in the code; it'd be effectively only for organizational purposes on the questionnaire owner's side
- the validation error message can (and should) be localized within the SPM package here; our questionnaires currently don't allow providing a custom error message for these uses (neither does FHIR); imo this should be kept that way

File: Sources/SpeziQuestionnaire/Model/Task.swift (hunk 7 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/Task.swift]: i wanted to support bounded multiple selection, but yeah for the time being it might be best to rmeove this, and then re-consider it at a later point

File: Sources/SpeziQuestionnaire/Model/Task.swift (hunk 8 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/Task.swift:85]: wdym exactly? why would the custom views be constrained to the fileAttachment task?

(there are some additional constraints/limitations/factors we need to operate within when it comes to custom question kinds; i'll go into that in depth in a separate issue)

File: Sources/SpeziQuestionnaireCatalog/PHQ9.swift
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaireCatalog/PHQ9.swift:1]: IMO since we currently only have 2 it's easier to include them in the main target. should we ever go beyond that, and start offering a larger amount of pre-defined questionnaires, we should move it at that point.

having a whole separate target for literally just 2 global variables and no actual logic feels like a litle overkill tbh

File: Sources/SpeziQuestionnaireCatalog/GAD7.swift (hunk 11 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaireCatalog/GAD7.swift:16]: (see also the other comment of mine a bit further up)

i guess the question here is what we ultimately consider as our primary source, ert where the questionnaires come from:
- if we want them primarily to be defined in Swift (and shipped hard-coded into an app): yes we should make everything `LocalizedStringResource`s, and build the entire API around that
- if we want to make it easy to convert them to/from JSON (and fetched dynamically from somewhere): it'd be much much easier and more convenient to simply use `String`s for everything (`LocalizedStringResource` technically _can_ be encoded/decoded, but it doesn't actually encode the whole locale -> value mapping, and instead simply encodes the key, table name, and bundle reference) which makes it useless if shared outside of the app itself


IMO the initial version should simply use `String`s everywhere, and require the client app to provide pre-localized `Questionnaire` instances, and we should then iterate on that if we want/need to (would be easier than the other way around)

File: Sources/SpeziQuestionnaire/Model/Task.swift (hunk 8 above)
Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaire/Model/Task.swift:85]: Oh, sorry for the missing context here. I was just referring to creating an GitHub issue that we also want to support custom views and elements in questionnaires and that might be an other case statement here in the Enum; nothing to do with the `fileAttachment` case.

File: Sources/SpeziQuestionnaire/Model/Task.swift (hunk 7 above)
Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaire/Model/Task.swift]: Might be good to make this a  follow-up issue 👍

File: Package.swift (hunk 3 above)
Comment (PSchmiedmayer) [reply Package.swift:74]: Sound good; thank you!

File: Sources/SpeziQuestionnaireCatalog/GAD7.swift (hunk 11 above)
Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaireCatalog/GAD7.swift:16]: I would argue that both input methods are valid and the local Swift one should assume localization using Swift/Xcode best practices using `LocalizedStringResources`; it might not be the primary way people define them but a very valid option and then manually handling localization feels strange and can't really take advantage of all the tooling.

The way they can be fetched from a local source would be the FHIR representation (multiple questionnaires, each for a different locale, then up to the user to fetch the right one for the right locale) or using a Coddle representation of our Questionnaire type. This one should then probably use out localization infrastructure that we added to SpeziFoundation that we also use in SpeziStudy to encode/decode elements from disk. If only a string is present in the decoding process, we can just naively map it to the current locale and assume that this was the intention of the developer.

File: Sources/SpeziQuestionnaireCatalog/PHQ9.swift
Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaireCatalog/PHQ9.swift:1]: I would see if as a way to already structure this in a nice way going forward, I would assume that they might get more complicated with localization in the near future and I would avoid a breaking change later down the line when we move them to a separate target; maybe a very small target for now but a good way to structure future contributions.

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift (hunk 6 above)
Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+InputValidation.swift:17]: Agree, error handling here is a bit tricky. I think it's fair to assume that the questionnaire will be in the correct locale (either based on our localization feature as described below) or the developer loaded the right questionnaire so IMO a good design decision to make this a `String`. And yes, all our own errors should be fully localized within the package.

File: Sources/SpeziQuestionnaireCatalog/PHQ9.swift
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaireCatalog/PHQ9.swift:1]: hmmm thats a good point; will do that. what should we call this extra target?
- `SpeziQuestionnaires` seems like a bad idea bc its super similar to the `SpeziQuestionnaire` main target
- `FHIRQuestionnaires` (the current name in RKoF) also seems like a bad idea, bc we aren't limited to FHIR questionnaires
- `SpeziSampleQuestionnaires` would make it sound like the target only contains demo questionnaires that aren't suitable for real-world usage

Comment (PSchmiedmayer) [reply Sources/SpeziQuestionnaireCatalog/PHQ9.swift:1]: How about `SpeziQuestionnaireCatalog`?

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift [hunk 12]
```diff
@@ -0,0 +1,228 @@
...
+    
+    private init(parent: QuestionnaireResponses, pathFromParent: ResponsesPath) {
+        questionnaire = parent.questionnaire
+        _variant = .view(parent: parent, pathFromParent: pathFromParent)
+    }
+    
+    
+    func view(appending path: ResponsesPath) -> Self {
+        Self(parent: self.root, pathFromParent: path)
+    }
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift:124]: wdym

[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift:124]: write me a small test case that reproduces this issue

File: Sources/SpeziQuestionnaireCatalog/GAD7.swift (hunk 11 above)
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaireCatalog/GAD7.swift:16]: will move localization into a separate PR and keep the current spproach (`String`s everywhere) for now. since we won't tag a new major just yet it'll be fine

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift (hunk 12 above)
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift:124]: why not fix it by passing in self instead of self.root for the parent

[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses.swift:124]: would the chaining still properly trigger swiftui view updates?

File: Sources/SpeziQuestionnaireFHIR/Questionnaire+FromFHIR.swift [hunk 13]
```diff
@@ -0,0 +1,491 @@
...
+                          let code = option.code.value?.string,
+                          let system = valueSet?.compose?.include.first?.system?.value?.url else {
+                        throw FHIRConversionError("Invalid Concept in answer option")
+                    }
+                    options.append(.init(
+                        id: code,
+                        title: display,
+                        subtitle: "", // could supply this via an extension
+                        fhirCoding: .init(system: system, code: code)
+                    ))
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaireFHIR/Questionnaire+FromFHIR.swift:284]: create a minimal trest case reproducign this issue

File: Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+Conditions.swift [hunk 14]
```diff
@@ -0,0 +1,289 @@
...
+    /// Looks up a ``Questionnaire/Task``, based on its id, in compliance with a ``TaskLookupConfig``.
+    private func resolveTaskId( // swiftlint:disable:this cyclomatic_complexity
+        targetTaskId: Questionnaire.Task.ID,
+        currentTaskId: Questionnaire.Task.ID,
+        using config: TaskLookupConfig
+    ) -> ResolvedTask? {
+        guard targetTaskId != currentTaskId else {
+            // A condition is never allowed to reference its own task
+            return nil
+        }
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/Model/QuestionnaireResponses+Conditions.swift:59]: generate a minimal test case reproducing this issue

File: Sources/SpeziQuestionnaire/UI/QuestionnaireSheet.swift [hunk 15]
```diff
@@ -0,0 +1,105 @@
...
+        ManagedNavigationStack {
+            if let section = questionnaire.sections.first {
+                QuestionnaireSectionView(
+                    questionnaire: questionnaire,
+                    section: section,
+                    completionStepConfig: completionStepConfig
+                ) { result in
+                    responses.purgeResponsesToDisabledTasks()
+                    await resultHandler(result)
+                    dismiss()
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/QuestionnaireSheet.swift:63]: why is this bad

[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziQuestionnaire/UI/QuestionnaireSheet.swift:63]: the externally passed in responses object never should contain responses for conditionally-disabled tasks to begin with
